### ISSUE TITLE
add some usage instructions

### ISSUE THREAD

**Issue by HugoP707** [ncn6mq/headless-rl#1]

**Comment by ncn6mq** [comment]
Sorry this project is unusable at the moment.  There are no graphics, and the physics are not even half-finished.  I've somewhat abandoned this in favor of making a Unity clone to accomplish the same purpose.  I'm leaving the repository up in case someone wants to look at it for reference, though.

**Comment by HugoP707** [comment]
i am up to date in this stuff, since i am in the discord server, but i would like to try yours nevertheless, maybe i try to add some graphics
